server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  port: 8090

spring:
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:E:/Data/H2/H2
    username: root
    password: 1234

  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ 설정
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Logging
logging:
  level:
    org:
      hibernate: info