server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  # H2 ??
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:mem:test
  url: jdbc:mariadb://localhost:3306/db
  driver-class-name: org.mariadb.jdbc.Driver
  username: root
  password: 1234

  # JPA ??
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ ??
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: xx.frame
      default-receive-queue: qq.frame
      routing-key: message

# Logging
logging:
  level:
    org:
      hibernate: info